apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwas-ss-logs-pv
  labels:
    name: gwas-ss-logs-pv
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/logs/"
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gwas-ss-service-claim0
  name: gwas-ss-service-claim0
spec:
  selector:
    matchLabels:
      name: gwas-ss-logs-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
