apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: gwas-ss-service
  name: gwas-ss-service
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  type: NodePort
  selector:
    io.kompose.service: gwas-ss-service
status:
  loadBalancer: {}
