language: python
python:
  - "3.6"
branches:
  only:
  - master
install:
  - pip install --force-reinstall -e .
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - pytest --cov-report html --cov sumstats_service --verbose
  - coverage xml
  - python-codacy-coverage -r coverage.xml
