language: python
python:
  - "3.6"
branches:
  only:
  - master
  - dev
services: 
  - rabbitmq
  - mongodb
addons:
  apt:
    packages:
      - rabbitmq-server
  sonarcloud:
    organization: "gwas-ebi"
install:
  - pip install --force-reinstall -e .
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - tox
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - sonar-scanner -Dsonar.organization=gwas-ebi -Dsonar.projectKey=gwas-sumstats-service -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=0566d66d0cfe16cd2cb8ba02db7fcd0b6d1e7ee6 -Dsonar.python.coverage.reportPaths=coverage.xml

