language: python
python:
  - "3.6"
branches:
  only:
  - master
services: rabbitmq
install:
  - pip install --force-reinstall -e .
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install gwas-sumstats-validator/
script:
  - tox
  - coverage xml
  - python-codacy-coverage -r coverage.xml
