language: python
python:
  - "3.6"
branches:
  only:
  - master
services: 
  - rabbitmq
  - mongodb
addons:
  apt:
    packages:
      - rabbitmq-server
install:
  - pip install --force-reinstall -e .
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - tox
  - coverage xml
  - python-codacy-coverage -r coverage.xml
