apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.worker.name}}
  namespace: {{.Values.k8Namespace}}
  lables:
    version: {{.Values.image.tag}}
spec:
  replicas: {{.Values.worker.replicaCount}}
  securityContext:
    runAsUser: {{.Values.image.uid}}
    runAsGroup: {{.Values.image.gid}}
  selector:
    matchLabels:
      app: {{.Values.worker.name}}
  template:
    metadata:
      labels:
        app: {{.Values.worker.name}}
    spec:
      containers:
      - name: {{.Values.worker.name}}
        image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        {{ if .Values.image.env.validateSSH }}
        command: ["celery", "-A", "sumstats_service.app.celery", "worker", "--loglevel=info", "--queues={{.Values.image.env.celeryQueue1}},{{.Values.image.env.celeryQueue2}}"]
        {{ else }}
        command: {{.Values.worker.celeryCmdPostOnly}}        
        {{ end }}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        resources:
          requests:
            cpu: {{.Values.resources.requests.cpu}}
            memory: {{.Values.resources.requests.memory}}
        volumeMounts:
        - mountPath: {{.Values.image.logMountPath}}
          name: log
        - mountPath: {{.Values.image.sshMountPath}}
          name: ssh
          readOnly: true
        - mountPath: {{.Values.image.dataMountPath}}
          name: data
          readOnly: false
        env:
        - name: CELERY_USER
          value: {{.Values.image.env.celeryUser}}
        - name: CELERY_PASSWORD
          value: {{.Values.image.env.celeryPwd}}
        - name: CELERY_QUEUE1
          value: {{.Values.image.env.celeryQueue1}}
        - name: CELERY_QUEUE2
          value: {{.Values.image.env.celeryQueue2}}
        - name: STORAGE_PATH
          value: {{.Values.image.env.storagePath}}
        - name: STAGING_PATH
          value: {{.Values.image.env.stagingPath}}
        - name: VALIDATED_PATH
          value: {{.Values.image.env.validatedPath}}
        - name: SW_PATH
          value: {{.Values.image.env.swPath}}
        - name: VALIDATE_WITH_SSH
          value: "{{.Values.image.env.validateSSH}}"
        - name: COMPUTE_FARM_LOGIN_NODE
          value: {{.Values.image.env.computeFarmLogin}}
        - name: COMPUTE_FARM_USERNAME
          value: {{.Values.image.env.computeFarmUser}}
        - name: COMPUTE_FARM_QUEUE_LONG
          value: {{.Values.image.env.computeFarmQueueLong}}
        - name: SINGULARITY_IMAGE
          value: {{.Values.image.repository}}
        - name: SINGULARITY_TAG
          value: {{.Values.image.tag}}
        - name: SINGULARITY_CACHEDIR
          value: {{.Values.image.singularityCache}}
        - name: REMOTE_HTTP_PROXY
          value: {{.Values.image.env.remoteHttpProxy}}
        - name: REMOTE_HTTPS_PROXY
          value: {{.Values.image.env.remoteHttpsProxy}}
        - name: FTP_SERVER
          value: {{.Values.image.env.ftpServer}}
        - name: FTP_USERNAME
          value: {{.Values.image.env.ftpUser}}
        - name: FTP_PASSWORD
          value: {{.Values.image.env.ftpPassword}}
        - name: MONGO_URI
          value: {{.Values.image.env.mongoURI}}
        - name: MONGO_USER
          value: {{.Values.image.env.mongoUser}}
        - name: MONGO_PASSWORD
          value: {{.Values.image.env.mongoPassword}}
        - name: MONGO_DB
          value: {{.Values.image.env.mongoDB}}
        - name: HTTP_PROXY
          value: {{.Values.image.env.httpProxy}}
        - name: HTTPS_PROXY
          value: {{.Values.image.env.httpsProxy}}
        - name: GLOBUS_SECRET
          value: {{.Values.image.env.globusSecret}}
        - name: TRANSFER_CLIENT_ID
          value: {{.Values.image.env.transferClientID}}
        - name: GWAS_GLOBUS_GROUP
          value: {{.Values.image.env.gwasGlobusGroup}}
        - name: CLIENT_ID
          value: {{.Values.image.env.clientID}}
        - name: GWAS_ENDPOINT_ID
          value: {{.Values.image.env.gwasEndpointID}}
        - name: UID
          value: {{.Values.image.uid}}
        - name: GID
          value: {{.Values.image.gid}}
        - name: USER
          value: {{.Values.image.user}}
      volumes:
      - name: log
        persistentVolumeClaim:
           claimName: {{ .Values.volume.log.ClaimName }}
      - name: ssh
        secret: 
           secretName: {{ .Values.secrets.sshName }}
           defaultMode: 0600
      - name: data
        nfs:
          server: {{ .Values.volume.data.nfsServer }}
          path: {{ .Values.volume.data.path }}
          readOnly: false
