# Default values for sumstats-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

image:
  repository: ebispot/gwas-sumstats-service
  tag: latest
  pullPolicy: Always
  containerPort: 8000
  logMountPath: "/sumstats_service/logs"
  dataMountPath: "/sumstats_service/data"
  sshMountPath: "/root/.ssh"
  globusTokenPath: "/sumstats_service/sumstats_service/resources/refresh-tokens.json"
  env:
    celeryUser: "username"
    celeryPwd: "password"
    storagePath: "./data"
    validateSSH: true
    computeFarmLogin: ""
    computeFarmUser: ""
    httpProxy: ""
    httpsProxy: ""
    gwasEndpointID: ""
    globusSecret: ""
    nativeClientID: ""
    clientID: ""
    

volume:
  log:
    ClaimName: gwas-depo-logs
  data:
    ClaimName: gwas-ss-data
    VolumeName: gwas-ss-service-data
    type: persistentVolumeClaim
    storageClassName: standard
    capacity:
      storage: 10Gi
    accessModes: ReadWriteOnce

secrets:
  sshName: ssh-keys
  globus: globus


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: gwas-ss-service
  type: ClusterIP
  port: 8000
  gunicornCmd: '["gunicorn", "-b", "0.0.0.0:8000", "sumstats_service.app:app", "-k=eventlet", "-t=100", "-w=2", "--log-level=debug","--access-logfile=logs/ss_access.log","--error-logfile=logs/ss_error.log"]'

worker:
  name: gwas-ss-worker
  celeryCmd: '["celery", "-A", "sumstats_service.app.celery", "worker", "--loglevel=debug", "--queues=preval,postval"]'
  celeryCmdPostOnly:  '["celery", "-A", "sumstats_service.app.celery", "worker", "--loglevel=debug", "--queues=postval"]'
  replicaCount: 1

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

k8Namespace: gwas

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

