apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwas-ss-service-pv
  labels:
    name: gwas-ss-service-pv
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
          path: "/path/to/data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gwas-ss-service-claim1
  name: gwas-ss-service-claim1
spec:
  selector:
    matchLabels:
      name: gwas-ss-service-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
